/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;

/**
 *
 * @author t.xiong
 */
public class CreateUserDialog extends javax.swing.JDialog {
    
    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    public void addPropertyChangeListener(PropertyChangeListener listener)
    {
        this.listeners.addPropertyChangeListener(listener);
    } 


    /**
     * Creates new form CreateUserDialog
     */
    public CreateUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newIdentifiantUser = new javax.swing.JTextField();
        labelIdentifiant = new javax.swing.JLabel();
        labelMotDePasse = new javax.swing.JLabel();
        btnValideAjoutUser = new javax.swing.JButton();
        newMotDePasseUser = new javax.swing.JPasswordField();
        newNomUser = new javax.swing.JTextField();
        labelIdentifiant1 = new javax.swing.JLabel();
        newPrenomUser = new javax.swing.JTextField();
        labelIdentifiant2 = new javax.swing.JLabel();
        newEmailUser = new javax.swing.JTextField();
        labelIdentifiant3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        verifNewMotDePasseUser = new javax.swing.JPasswordField();
        labelMotDePasse1 = new javax.swing.JLabel();
        checkboxShowNewMotDePasse = new javax.swing.JCheckBox();
        checkboxShowVerifNewMotDePasse = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(500, 500));

        labelIdentifiant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant.setText("Identifiant");

        labelMotDePasse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMotDePasse.setText("Mot de passe");

        btnValideAjoutUser.setText("Confirmer");
        btnValideAjoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValideAjoutUserActionPerformed(evt);
            }
        });

        newMotDePasseUser.setText("jPasswordField1");

        labelIdentifiant1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant1.setText("Nom");

        labelIdentifiant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant2.setText("Prenom");

        labelIdentifiant3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant3.setText("Email");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ajout utilisateur");

        verifNewMotDePasseUser.setText("jPasswordField1");

        labelMotDePasse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMotDePasse1.setText("Verification du mot de passe");

        checkboxShowNewMotDePasse.setText("Show passwrd");
        checkboxShowNewMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowNewMotDePasseActionPerformed(evt);
            }
        });

        checkboxShowVerifNewMotDePasse.setText("Show passwrd");
        checkboxShowVerifNewMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowVerifNewMotDePasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(labelIdentifiant)
                    .addComponent(newIdentifiantUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentifiant1)
                    .addComponent(newNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentifiant2)
                    .addComponent(newPrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentifiant3)
                    .addComponent(newEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMotDePasse)
                    .addComponent(newMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMotDePasse1)
                    .addComponent(verifNewMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxShowNewMotDePasse)
                    .addComponent(checkboxShowVerifNewMotDePasse))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnValideAjoutUser)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelIdentifiant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newIdentifiantUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelIdentifiant1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newNomUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelIdentifiant2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPrenomUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelIdentifiant3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newEmailUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelMotDePasse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMotDePasseUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxShowNewMotDePasse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMotDePasse1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifNewMotDePasseUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxShowVerifNewMotDePasse))
                .addGap(18, 18, 18)
                .addComponent(btnValideAjoutUser)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValideAjoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValideAjoutUserActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("ValideAjoutUser", null, null);
    }//GEN-LAST:event_btnValideAjoutUserActionPerformed

    private void checkboxShowNewMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowNewMotDePasseActionPerformed
        // TODO add your handling code here:
        if(checkboxShowNewMotDePasse.isSelected()){
            newMotDePasseUser.setEchoChar((char)0);
        }
        else{
            newMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowNewMotDePasseActionPerformed

    private void checkboxShowVerifNewMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowVerifNewMotDePasseActionPerformed
        // TODO add your handling code here:
        if(checkboxShowNewMotDePasse.isSelected()){
            verifNewMotDePasseUser.setEchoChar((char)0);
        }
        else{
            verifNewMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowVerifNewMotDePasseActionPerformed

    public void setDefaultData()
    {
        this.newIdentifiantUser.setText("");
        this.newNomUser.setText("");
        this.newPrenomUser.setText("");
        this.newEmailUser.setText("");
        this.newMotDePasseUser.setText("");
        this.verifNewMotDePasseUser.setText("");
        
        this.checkboxShowNewMotDePasse.setSelected(false);
        this.newMotDePasseUser.setEchoChar('*');
        this.checkboxShowVerifNewMotDePasse.setSelected(false);
        this.verifNewMotDePasseUser.setEchoChar('*');
    }
    
    public int verifForm() {
        if (newIdentifiantUser.getText().equals("") || 
                newNomUser.getText().equals("") ||
                newPrenomUser.getText().equals("") ||
                newEmailUser.getText().equals("") || 
                String.valueOf(this.newMotDePasseUser.getPassword()).equals("")){
            return 1;
        }
        
        else if (!String.valueOf(this.newMotDePasseUser.getPassword()).equals(String.valueOf(this.verifNewMotDePasseUser.getPassword()))) {
            return 2;
        }
        
        else {
            return 3;
        }
    }
    
    public void erreurChamps(){
        JOptionPane.showMessageDialog(this, "Champs de saisie obligatoire !");
    }
    
    public void erreurMDP(){
        JOptionPane.showMessageDialog(this, "Vérification du mot de passe incorrect !");
    }
    
    public String getIdentifiantUser()
    {
        return this.newIdentifiantUser.getText();
    }
    
    public String getNomUser(){
        return this.newNomUser.getText();
    }
    
    public String getPrenomUser(){
        return this.newPrenomUser.getText();
    }
    
    public String getEmailUser(){
        return this.newEmailUser.getText();
    }
    
    public String getMotDePasseUser()
    {
        return String.valueOf(this.newMotDePasseUser.getPassword());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateUserDialog dialog = new CreateUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValideAjoutUser;
    private javax.swing.JCheckBox checkboxShowNewMotDePasse;
    private javax.swing.JCheckBox checkboxShowVerifNewMotDePasse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIdentifiant;
    private javax.swing.JLabel labelIdentifiant1;
    private javax.swing.JLabel labelIdentifiant2;
    private javax.swing.JLabel labelIdentifiant3;
    private javax.swing.JLabel labelMotDePasse;
    private javax.swing.JLabel labelMotDePasse1;
    private javax.swing.JTextField newEmailUser;
    private javax.swing.JTextField newIdentifiantUser;
    private javax.swing.JPasswordField newMotDePasseUser;
    private javax.swing.JTextField newNomUser;
    private javax.swing.JTextField newPrenomUser;
    private javax.swing.JPasswordField verifNewMotDePasseUser;
    // End of variables declaration//GEN-END:variables
}
