/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author t.xiong
 */
public class MainView extends javax.swing.JFrame {

    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);
    
    public void addPropertyChangeListener(PropertyChangeListener listener)
    {
        listeners.addPropertyChangeListener(listener);
    }
    
    public String message(String message){
        return message;
    }
    
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }
    
    public void setTableModel (AbstractTableModel tableModel)
    {
        this.usersList.setModel (tableModel);
        this.usersList.removeColumn(this.usersList.getColumn("Id_utilisateur"));
        this.usersList.removeColumn(this.usersList.getColumn("Mot_de_passe"));
        
    }
    
    public int getSelectedId(){
        return (Integer) this.usersList.getModel().getValueAt(this.usersList.getSelectedRow(), 0);
    }
    public String getSelectedIdentifant(){
        return (String) this.usersList.getModel().getValueAt(this.usersList.getSelectedRow(), 1);
    }
    public String getSelectedNom(){
        return (String) this.usersList.getModel().getValueAt(this.usersList.getSelectedRow(), 2);
    }
    public String getSelectedPrenom(){
        return (String) this.usersList.getModel().getValueAt(this.usersList.getSelectedRow(), 3);
    }
    public String getSelectedEmail(){
        return (String) this.usersList.getModel().getValueAt(this.usersList.getSelectedRow(), 4);
    }
    public String getSelectedMotDePasse(){
        return (String) this.usersList.getModel().getValueAt(this.usersList.getSelectedRow(), 5);
    }
    
//    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//    nouvel attributs
    public String getSelectedAttributs(){
        return (String) this.usersList.getModel().getValueAt(this.usersList.getSelectedRow(), 6);
    }
//    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenDialogAjoutUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JTable();
        btnOpenDialogModifUser = new javax.swing.JButton();
        btnOpenDialogSuppUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOpenDialogAjoutUser.setText("Ajout");
        btnOpenDialogAjoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDialogAjoutUserActionPerformed(evt);
            }
        });

        usersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(usersList);

        btnOpenDialogModifUser.setText("Modification");
        btnOpenDialogModifUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDialogModifUserActionPerformed(evt);
            }
        });

        btnOpenDialogSuppUser.setText("Supprimer");
        btnOpenDialogSuppUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDialogSuppUserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Liste des utilisateurs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnOpenDialogModifUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpenDialogSuppUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOpenDialogAjoutUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenDialogAjoutUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpenDialogModifUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpenDialogSuppUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenDialogAjoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDialogAjoutUserActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("OpenDialogAjoutUser", null, null);
    }//GEN-LAST:event_btnOpenDialogAjoutUserActionPerformed

    private void btnOpenDialogModifUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDialogModifUserActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("OpenDialogModifUser", null, null);
    }//GEN-LAST:event_btnOpenDialogModifUserActionPerformed

    private void btnOpenDialogSuppUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDialogSuppUserActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Êtes vous sur de vouloir supprimer cet utilisateur ?");
        if (reponse == JOptionPane.YES_OPTION) {
            
            listeners.firePropertyChange("validSuppUser", null, null);
            
            
            JOptionPane.showMessageDialog(this, "Cet utilisateur a était supprimé");
        }
    }//GEN-LAST:event_btnOpenDialogSuppUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenDialogAjoutUser;
    private javax.swing.JButton btnOpenDialogModifUser;
    private javax.swing.JButton btnOpenDialogSuppUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable usersList;
    // End of variables declaration//GEN-END:variables
}
