/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;

/**
 *
 * @author t.xiong
 */
public class UpdateUserDialog extends javax.swing.JDialog {

    /**
     * Creates new form UpdateUserDialog
     */
    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    private int id;

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        this.listeners.addPropertyChangeListener(listener);
    }

    public UpdateUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setIdUser(int id) {
        this.id = id;
    }
    public int getIdUser() {
        return this.id;
    }
    
//    set la valeur de l'ifentifiant
    public void setIdentifiantUser(String identifiant) {
        this.modifIdentifiantUser.setText(identifiant);
    }
//    Récupére la nouvelle valeur de l'identifiant
    public String getIdentifiantUser() {
        return this.modifIdentifiantUser.getText();
    }
    
    public void setNomUser(String nom){
        this.modifNomUser.setText(nom);
    }
    public String getNomUser(){
        return this.modifNomUser.getText();
    }
    
    public void setPrenomUser(String prenom){
        this.modifPrenomUser.setText(prenom);
    }
    public String getPrenomUser(){
        return this.modifPrenomUser.getText();
    }
    
    public void setEmailUser(String email){
        this.modifEmailUser.setText(email);
    }
    public String getEmailUser(){
        return this.modifEmailUser.getText();
    }
    
    public void setMotDePasseUser(String motDePasse) {
        this.modifMotDePasseUser.setText(motDePasse);
    }
    public String getMotDePasseUser(){
        return String.valueOf(this.modifMotDePasseUser.getPassword());
    }
    
//    attribut les valeurs par défault
    public void setDefaultData(){
        this.verifModifMotDePasseUser.setText("");
        this.checkboxShowMotDePasse.setSelected(false);
        this.modifMotDePasseUser.setEchoChar('*');
        this.checkboxShowVerifMotDePasse.setSelected(false);
        this.verifModifMotDePasseUser.setEchoChar('*');
    }
//    Retourne vrai si les nouveau mot de passe sont identiques et non vide
    public int verifForm() {
        if (modifIdentifiantUser.getText().equals("") || 
                modifNomUser.getText().equals("") ||
                modifPrenomUser.getText().equals("") ||
                modifEmailUser.getText().equals("") || 
                String.valueOf(this.modifMotDePasseUser.getPassword()).equals("")){
            return 1;
        }
        
        else if (!String.valueOf(this.modifMotDePasseUser.getPassword()).equals(String.valueOf(this.verifModifMotDePasseUser.getPassword()))) {
            return 2;
        }
        
        else {
            return 3;
        }
    }
    
    public void erreurChamps(){
        JOptionPane.showMessageDialog(this, "Champs de saisie obligatoire !");
    }
    public void erreurMDP(){
        JOptionPane.showMessageDialog(this, "Vérification du mot de passe incorrect !");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIdentifiant = new javax.swing.JLabel();
        modifIdentifiantUser = new javax.swing.JTextField();
        labelMotDePasse = new javax.swing.JLabel();
        btnValideAjoutUser = new javax.swing.JButton();
        modifMotDePasseUser = new javax.swing.JPasswordField();
        verifModifMotDePasseUser = new javax.swing.JPasswordField();
        labelMotDePasse2 = new javax.swing.JLabel();
        checkboxShowMotDePasse = new javax.swing.JCheckBox();
        checkboxShowVerifMotDePasse = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        modifNomUser = new javax.swing.JTextField();
        labelIdentifiant1 = new javax.swing.JLabel();
        modifPrenomUser = new javax.swing.JTextField();
        labelIdentifiant2 = new javax.swing.JLabel();
        labelIdentifiant3 = new javax.swing.JLabel();
        modifEmailUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(500, 500));

        labelIdentifiant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant.setText("Identifiant");
        labelIdentifiant.setPreferredSize(new java.awt.Dimension(54, 22));

        labelMotDePasse.setText("Mot de passe");

        btnValideAjoutUser.setText("Confirmer");
        btnValideAjoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValideAjoutUserActionPerformed(evt);
            }
        });

        modifMotDePasseUser.setText("jPasswordField1");

        verifModifMotDePasseUser.setText("jPasswordField1");

        labelMotDePasse2.setText("Verification du mot de passe");

        checkboxShowMotDePasse.setText("Show passwrd");
        checkboxShowMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowMotDePasseActionPerformed(evt);
            }
        });

        checkboxShowVerifMotDePasse.setText("Show passwrd");
        checkboxShowVerifMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxShowVerifMotDePasseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Modification utilisateur");

        labelIdentifiant1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant1.setText("Nom");

        labelIdentifiant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant2.setText("Prenom");

        labelIdentifiant3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentifiant3.setText("Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnValideAjoutUser)
                    .addComponent(verifModifMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMotDePasse2)
                    .addComponent(modifMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMotDePasse)
                    .addComponent(modifEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentifiant3)
                    .addComponent(modifPrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentifiant2)
                    .addComponent(modifNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentifiant1)
                    .addComponent(modifIdentifiantUser, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxShowMotDePasse)
                    .addComponent(checkboxShowVerifMotDePasse))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifIdentifiantUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelIdentifiant1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelIdentifiant2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifPrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelIdentifiant3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMotDePasse)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifMotDePasseUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxShowMotDePasse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMotDePasse2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifModifMotDePasseUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxShowVerifMotDePasse))
                .addGap(18, 18, 18)
                .addComponent(btnValideAjoutUser)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValideAjoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValideAjoutUserActionPerformed
        // TODO add your handling code here:
        listeners.firePropertyChange("ValideModifUser", null, null);
    }//GEN-LAST:event_btnValideAjoutUserActionPerformed

    private void checkboxShowMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowMotDePasseActionPerformed
        // TODO add your handling code here:
        if(checkboxShowMotDePasse.isSelected()){
            modifMotDePasseUser.setEchoChar((char)0);
        }
        else{
            modifMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowMotDePasseActionPerformed

    private void checkboxShowVerifMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxShowVerifMotDePasseActionPerformed
        // TODO add your handling code here:
        if(checkboxShowVerifMotDePasse.isSelected()){
            verifModifMotDePasseUser.setEchoChar((char)0);
        }
        else{
            verifModifMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxShowVerifMotDePasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateUserDialog dialog = new UpdateUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValideAjoutUser;
    private javax.swing.JCheckBox checkboxShowMotDePasse;
    private javax.swing.JCheckBox checkboxShowVerifMotDePasse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIdentifiant;
    private javax.swing.JLabel labelIdentifiant1;
    private javax.swing.JLabel labelIdentifiant2;
    private javax.swing.JLabel labelIdentifiant3;
    private javax.swing.JLabel labelMotDePasse;
    private javax.swing.JLabel labelMotDePasse2;
    private javax.swing.JTextField modifEmailUser;
    private javax.swing.JTextField modifIdentifiantUser;
    private javax.swing.JPasswordField modifMotDePasseUser;
    private javax.swing.JTextField modifNomUser;
    private javax.swing.JTextField modifPrenomUser;
    private javax.swing.JPasswordField verifModifMotDePasseUser;
    // End of variables declaration//GEN-END:variables
}
